# Overrides for Development
version: '3.8'

services:
  em_service_www:
    volumes:
      - './nginx/certs/cacerts.crt:/usr/local/share/ca-certificates/cacerts.crt'
      - './nginx:/etc/nginx'

  em_service_registry:
    volumes:
      - ./shared/consul/leader/config:/consul/config
      - ./shared/consul/leader/certs:/consul/certs

  em_service_idweb:
   environment:
      - ASPNETCORE_ENVIRONMENT=Development
   volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - './src/EventManager.Identity.Admin/certs:/root/.dotnet/https:ro'
      - './src/EventManager.Identity.Admin/certs/cacerts.crt:/usr/local/share/ca-certificates/cacerts.crt:ro'
   command: dotnet EventManager.Identity.Admin.dll /seed
#   labels:
#      com.microsoft.visualstudio.debuggee.arguments: ' --additionalProbingPath /root/.nuget/packages --additionalProbingPath /root/.nuget/fallbackpackages  "bin/Debug/net5.0/EventManager.Identity.Admin.dll" /seed'
  
  em_service_idapi:
   environment:
      - ASPNETCORE_ENVIRONMENT=Development
   volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - './src/EventManager.Identity.Admin.Api/certs:/root/.dotnet/https:ro'
      - './src/EventManager.Identity.Admin.Api/certs/cacerts.crt:/usr/local/share/ca-certificates/cacerts.crt:ro'

  em_service_sts:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - './src/EventManager.Identity.STS.Identity/certs:/root/.dotnet/https:ro'
      - './src/EventManager.Identity.STS.Identity/certs/cacerts.crt:/usr/local/share/ca-certificates/cacerts.crt:ro'
